### ISSUE TITLE
Create a Github actions script?

### ISSUE THREAD

**Issue by simonrolph** [BiologicalRecordsCentre/recorder-feedback-content#2]

**Comment by simonrolph** [comment]
This is likely feasible, however there are security/privacy implications about generating PERSONAL feedback. However this could work for generic population level feedback. The other issue is that sensetive information is held in config.yml which would need to use github secrets https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions Here's what chatgpt had to say:

Here’s a GitHub Actions workflow to run your R script in a CI/CD pipeline. The workflow includes steps to set up R, install dependencies, and execute the script.

### GitHub Actions Workflow (`.github/workflows/r-pipeline.yml`)
```yaml
name: Recorder Feedback Delivery Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  r-pipeline:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up R environment
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.0' # Specify the R version you are using

    # Step 3: Install system dependencies
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev pandoc

    # Step 4: Install R dependencies using `renv`
    - name: Restore R dependencies
      run: |
        Rscript -e "install.packages('renv', repos = 'https://cloud.r-project.org')"
        Rscript -e "renv::restore()"

    # Step 5: Run the R script
    - name: Run R script
      env:
        R_CONFIG_ACTIVE: "default" # Set your desired configuration environment
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }} # Use GitHub secrets for sensitive information
      run: |
        Rscript -e "rmarkdown::render('run_pipeline.Rmd')"

    # Step 6: Upload artefacts (Optional)
    - name: Upload outputs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: pipeline-outputs
        path: |
          renders/
          data/
```

### Key Points:
1. **Environment Variables**: 
   - Use `env:` to pass configuration variables. Replace `R_CONFIG_ACTIVE` and `SMTP_PASSWORD` with the appropriate values or secrets.

2. **Secrets**:
   - Add sensitive information like API keys, database passwords, or SMTP credentials as GitHub secrets (`Settings > Secrets and variables > Actions`).

3. **Artefacts**:
   - Upload generated files or reports (`renders/`, `data/`) as artefacts for download.

4. **Dependencies**:
   - System-level dependencies (`libcurl4-openssl-dev`, etc.) and R dependencies (`renv::restore()`) ensure your environment is consistent.

5. **R Version**:
   - Specify the R version in the `setup-r` step to match your development environment.

This workflow will automatically execute your pipeline whenever code is pushed to the `main` branch or a pull request is created. Let me know if you'd like additional adjustments!
